CREATE TABLE Club
(
	C_ID INTEGER NOT NULL AUTO_INCREMENT,
	Name VARCHAR(10),
	City VARCHAR(10),
	Rank INTEGER,
	CONSTRAINT PRIMARY KEY (C_ID)
);

CREATE TABLE Player
(
	P_ID INTEGER AUTO_INCREMENT,
	Number INTEGER,
	Name VARCHAR(30),
	Age INTEGER,
Match_Played INTEGER,
Goals INTEGER,
	Position VARCHAR(10),
	Club INTEGER,
	CONSTRAINT PRIMARY KEY (P_ID),
	FOREIGN KEY (Club) REFERENCES Club (C_ID) ON DELETE CASCADE
);

CREATE TABLE Game_Played
(
	G_ID INTEGER AUTO_INCREMENT,
	Date DATE,
	Points INTEGER,
	Win VARCHAR(5),
	Lost VARCHAR(5),
	Draw INTEGER DEFAULT 0,
	Home INTEGER,
	Visit INTEGER,
	CONSTRAINT PRIMARY KEY (G_ID),
	FOREIGN KEY (Home) REFERENCES Club (C_ID) ON DELETE CASCADE,
	FOREIGN KEY (Visit) REFERENCES Club (C_ID) ON DELETE CASCADE
);

CREATE TABLE Game_Event
(
	E_ID INTEGER AUTO_INCREMENT,
	G_ID INTEGER,
	EVENT VARCHAR(20),
	Player INTEGER,
	Time TIME(0),
	Date DATE,
	CONSTRAINT PRIMARY KEY (E_ID),
	FOREIGN KEY (G_ID) REFERENCES Game_Played (G_ID) ON DELETE CASCADE,
	FOREIGN KEY (Player) REFERENCES Player (P_ID) ON DELETE CASCADE
);

CREATE TABLE Staff
(
	Club INTEGER,
	Owner VARCHAR (30),
	Head_Coach VARCHAR (20),
	Assistant_Coach VARCHAR(20),
Medical_Head VARCHAR(20), 
	CONSTRAINT PRIMARY KEY (Club),
	FOREIGN KEY (Club) REFERENCES Club(C_ID) ON DELETE CASCADE
);

CREATE TABLE Upcoming_Game
(
	U_ID INTEGER AUTO_INCREMENT,
	Date DATE,
	Time TIME(0),
	Home INTEGER,
	Visit INTEGER,
	CONSTRAINT PRIMARY KEY (U_ID),
	FOREIGN KEY (Home) REFERENCES Club(C_ID) ON DELETE CASCADE,
	FOREIGN KEY (Visit) REFERENCES Club(C_ID) ON DELETE CASCADE
);
